const music = [
  {
    music_id: 1,
    title: 'Hey Ya',
    performer: 'Outkast',
    level: 'Easy',
    src: "./assets/audio/hey-ya-outkast.mp3",
  },
  {
    music_id: 2,
    title: 'In Da club',
    performer: '50 Cent',
    level: 'Easy',
    src: "./assets/audio/in-da-club-50-cent.mp3",
  },
  {
    music_id: 3,
    title: 'Happy',
    performer: 'Pharell Williams',
    level: 'Easy',
    src: "./assets/audio/happy-pharell-williams.mp3",
  },
  {
    music_id: 4,
    title: 'Somebody That I Used to Know',
    performer: 'Gotye',
    level: 'Easy',
    src: "./assets/audio/somebody-that-i-used-to-know-gotye.mp3",
  },
  {
    music_id: 5,
    title: 'Rolling In The Deep',
    performer: 'Adele',
    level: 'Easy',
    src: "./assets/audio/rolling-in-the-deep-adele.mp3",
  },
  {
    music_id: 6,
    title: 'Billie Jean',
    performer: 'Michael Jackson',
    level: 'Easy',
    src: "./assets/audio/billie-jean-michael-jackson.mp3",
  },
  {
    music_id: 7,
    title: 'Smells Like Teen Spirit',
    performer: 'Nirvana',
    level: 'Easy',
    src: "./assets/audio/smells-like-teen-spirit-nirvana.mp3",
  },
  {
    music_id: 8,
    title: 'Crazy In Love',
    performer: 'Beyonce',
    level: 'Easy',
    src: "./assets/audio/crazy-in-love-beyonce.mp3",
  },
  {
    music_id: 9,
    title: 'Bad Romance',
    performer: 'Lady Gaga',
    level: 'Easy',
    src: "./assets/audio/bad-romance-lady-gaga.mp3",
  },
  {
    music_id: 10,
    title: 'Pelados Em Santos',
    performer: 'Mamonas Assassinas',
    level: 'Easy',
    src: "./assets/audio/pelados-em-santos-mamonas-assassinas.mp3",
  },
  {
    music_id: 11,
    title: 'Que País É Esse?',
    performer: 'Legião Urbana',
    level: 'Easy',
    src: "./assets/audio/que-pais-e-esse-legiao-urbana.mp3",
  },
  {
    music_id: 12,
    title: 'Preciso Me Encontrar',
    performer: 'Cartola',
    level: 'Easy',
    src: "./assets/audio/preciso-me-encontrar-cartola.mp3",
  },
  {
    music_id: 13,
    title: 'Garota De Ipanema',
    performer: 'Tom Jobim',
    level: 'Easy',
    src: "./assets/audio/garota-de-ipanema-tom-jobim.mp3",
  },
  {
    music_id: 14,
    title: 'Balada Boa',
    performer: 'Gusttavo Lima',
    level: 'Easy',
    src: "./assets/audio/balada-boa-gusttavo-lima.mp3",
  },
  {
    music_id: 15,
    title: 'Anna Júlia',
    performer: 'Los Hermanos',
    level: 'Easy',
    src: "./assets/audio/anna-julia-los-hermanos.mp3",
  },
  {
    music_id: 16,
    title: 'Ai Se Eu Te Pego',
    performer: 'Michel Teló',
    level: 'Easy',
    src: "./assets/audio/ai-se-eu-te-pego-michel-telo.mp3",
  },
  {
    music_id: 17,
    title: 'Cheia De Manias',
    performer: 'Raça Negra',
    level: 'Easy',
    src: "./assets/audio/cheia-de-manis-raca-negra.mp3",
  },
];