const movies = [
    {
    title: 'Mamonas',
    author: ,
    level: ,
    src: ,
    },
    title: 'The Godfather',
    author: 1972,
    level: 'Francis Ford Coppola',
    src: '2h 55min',
    },
    title: 'The Godfather',
    author: 1972,
    level: 'Francis Ford Coppola',
    src: '2h 55min',
    },
    title: 'The Godfather',
    author: 1972,
    level: 'Francis Ford Coppola',
    src: '2h 55min',
    },
    title: 'The Godfather',
    author: 1972,
    level: 'Francis Ford Coppola',
    src: '2h 55min',
    },
    title: 'The Godfather',
    author: 1972,
    level: 'Francis Ford Coppola',
    src: '2h 55min',
    },
    title: 'The Godfather',
    author: 1972,
    level: 'Francis Ford Coppola',
    src: '2h 55min',
    },
    {
      title: 'The Godfather',
      author: 1972,
      level: 'Francis Ford Coppola',
      src: '2h 55min',
    }
  ];